//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montage.Weiss.Tools.Resources.TTS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TTSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TTSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Montage.Weiss.Tools.Resources.TTS.TTSResources", typeof(TTSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CustomObject {
            get {
                object obj = ResourceManager.GetObject("CustomObject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Deck Generator Tool v0.0.1
        ///-- This script was inspired by Card Naming Tool which was created by dzikakulka, 
        ///-- and co-authored and published by Hiram Abiff.
        ///-- Created specifically for wstools, do not edit unless you know what you&apos;re doing.
        ///
        ///deckName = &lt;deck_name_info_placeholder&gt;
        ///serialsJSON = &lt;serials_placeholder&gt;
        ///serialInfoJSON = &lt;serial_info_placeholder&gt;
        ///
        ///-- Unless looking to troubleshoot, everything below this point should not need to be changed.
        ///windowName = &quot;deckGeneratorWindow&quot;
        ///defaul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LuaTemplate {
            get {
                return ResourceManager.GetString("LuaTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeissSchwarzLogo {
            get {
                object obj = ResourceManager.GetObject("WeissSchwarzLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Defaults&gt;
        ///  &lt;Panel class=&quot;Window&quot; width=&quot;400&quot; height=&quot;175&quot; color=&quot;#FFFFFF40&quot; outline=&quot;#404040&quot;/&gt;
        ///  &lt;Panel class=&quot;TopBar&quot; height=&quot;30&quot; rectAlignment=&quot;UpperCenter&quot; color=&quot;#191970&quot;/&gt;
        ///  &lt;Text class=&quot;WindowTitle&quot; fontSize=&quot;18&quot; height=&quot;20&quot; fontStyle=&quot;Bold&quot; rectAlignment=&quot;UpperCenter&quot; color=&quot;#FFFFFF&quot; /&gt;
        ///  &lt;Button class=&quot;topButtons&quot; width=&quot;20&quot; height=&quot;20&quot; rectAlignment=&quot;UpperRight&quot; color=&quot;#eeeeee&quot;/&gt;
        ///&lt;/Defaults&gt;
        ///
        ///&lt;Panel class=&quot;Window&quot; id=&quot;deckGeneratorWindow&quot; allowDragging=&quot;True&quot; returnToOriginalPositionWhenR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLUITemplate {
            get {
                return ResourceManager.GetString("XMLUITemplate", resourceCulture);
            }
        }
    }
}
