name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter TestCategory\!=Manual
    - name: Publish
      run: |
        dotnet publish ./Montage.Weiss.Tools/Montage.Weiss.Tools.csproj -c Release -r win-x64 -o publish -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --version-suffix 'rc${{ github.run_number }}'
        dotnet publish ./Montage.Weiss.Tools/Montage.Weiss.Tools.csproj -c Release -r linux-x64 -o publish -p:PublishSingleFile=true  -p:PublishTrimmed=false  --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --version-suffix 'rc${{ github.run_number }}'
        dotnet publish ./Montage.Weiss.Tools.GUI/Montage.Weiss.Tools.GUI.csproj -c Release -f net10.0-windows -r win-x64 -o publish -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --version-suffix 'rc${{ github.run_number }}'
        dotnet publish ./Montage.Weiss.Tools.GUI/Montage.Weiss.Tools.GUI.csproj -c Release -f net10.0 -r linux-x64 -o publish -p:PublishSingleFile=true  -p:PublishTrimmed=false  --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --version-suffix 'rc${{ github.run_number }}'
    - name: Upload Artifact (wstools win-x64)
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v6
      with:
        name: wstools-win-x64
        path: publish/wstools.exe
        if-no-files-found: warn
    - name: Upload Artifact (wstools linux-x64)
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v6
      with:
        name: wstools-linux-x64
        path: publish/wstools
        if-no-files-found: warn
    - name: Upload Artifact (wsm-gui win-x64)
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v6
      with:
        name: wsm-gui-win-x64
        path: publish/wsm-gui.exe
        if-no-files-found: warn
    - name: Upload Artifact (wsm-gui linux-x64)
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v6
      with:
        name: wsm-gui-linux-x64
        path: publish/wsm-gui
        if-no-files-found: warn
